=== xmarv023/Znackovaci-jazyky/XMLSchema.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="databazeNastaveniUzivatelu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nastaveni" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="nastaveni">
        <xs:complexType>
            <xs:sequence>
                <xs:annotation>
                  <xs:documentation>Nastaveni hry Euro Truck Simulator 2</xs:documentation>
                </xs:annotation>
                <xs:element name="zobrazeni">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="cela_obrazovka" type="xs:boolean" />
                      <xs:element name="jas">
                         <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minExclusive value="0"/>
                                <xs:maxInclusive value="100"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="rozliseni">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                                <xs:enumeration value="1080p"/>
                                <xs:enumeration value="720p"/>
                                <xs:enumeration value="480p"/>
                          </xs:restriction>                  
                        </xs:simpleType>
                      </xs:element>
                      <xs:element name="obnovovaci_frekvence">
                          <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minExclusive value="30"/>
                                <xs:maxInclusive value="200"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="vertikalni_synchronizace" type="xs:boolean"/>
                      <xs:element name="MLAA" type="xs:boolean"/>
                      <xs:element name="HDR" type="xs:boolean"/>
                      <xs:element name="DOF" type="xs:boolean"/>
                      <xs:element name="slunecni_paprsky" type="xs:boolean"/>
                      <xs:element name="korekce_barev" type="xs:boolean"/>
                      <xs:element name="detaily_odlesku">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Střední"/>
                                    <xs:enumeration value="Vysoká"/>
                            </xs:restriction>
                        </xs:simpleType>
                      </xs:element>
                      <xs:element name="kvalita_vegetace">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Střední"/>
                                    <xs:enumeration value="Vysoká"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="hustota_travy">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Vypnuto"/>
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Vysoká"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="kvalita_stinu">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Vypnuto"/>
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Střední"/>
                                    <xs:enumeration value="Vysoká"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="velikost_stinove_textury">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Vysoká"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="kvalita_pocasi">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Střední"/>
                                    <xs:enumeration value="Vysoká"/>
                                    <xs:enumeration value="Ultra"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="kvalita_zrcatek">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Střední"/>
                                    <xs:enumeration value="Vysoká"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="vykreslovana_vzdalenost_zrcatek">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Střední"/>
                                    <xs:enumeration value="Vysoká"/>
                                    <xs:enumeration value="Ultra"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="kvalita_textur">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Střední"/>
                                    <xs:enumeration value="Vysoká"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="anizotropni_filtrovani">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minExclusive value="0"/>
                                <xs:maxInclusive value="100"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="normalove_mapovani" type="xs:boolean"/>
                      <xs:element name="hlavni_svetla_vozidel" type="xs:boolean"/>
                      <xs:element name="vedlejsi_svetla_vozidel" type="xs:boolean"/>
                      <xs:element name="vykreslovana_vzdalenost_svetel">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                    <xs:enumeration value="Vypnuto"/>
                                    <xs:enumeration value="Nízká"/>
                                    <xs:enumeration value="Střední"/>
                                    <xs:enumeration value="Vysoká"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="chodci" type="xs:boolean"/>
                    </xs:sequence>
                    <xs:attribute name="api">
                        <xs:simpleType>
                            <xs:restriction base="xs:string"/>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="default-zobrazeni">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="no"/>
                                <xs:enumeration value="yes"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                  </xs:complexType>
                </xs:element>
                <xs:element name="zvuk">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="celkova_hlasitost">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minExclusive value="0"/>
                                <xs:maxInclusive value="100"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="hlasitost_efektu">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minExclusive value="0"/>
                                <xs:maxInclusive value="100"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="hlasitost_hudby">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minExclusive value="0"/>
                                <xs:maxInclusive value="100"/>
                            </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                      <xs:element name="prevratit_stereo" type="xs:boolean"/>
                      <xs:element name="zvukove_efekty" type="xs:boolean"/>
                      <xs:element name="hudba" type="xs:boolean"/>
                      <xs:element name="zvukovy_signal_pri_couvani" type="xs:boolean"/>                        
                      <xs:element name="hlucne_vodici_cary" type="xs:boolean"/>
                    </xs:sequence>
                    <xs:attribute name="vystup">
                        <xs:simpleType>
                                <xs:restriction base="xs:string">
                                      <xs:enumeration value="reproduktor"/>
                                      <xs:enumeration value="sluchatka"/>
                                </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="default-zvuk">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="no"/>
                                <xs:enumeration value="yes"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                  </xs:complexType>
                </xs:element>
                
            </xs:sequence>
            <xs:attribute name="iduzivatele">
                <xs:simpleType>
                        <xs:restriction base="xs:nonNegativeInteger">
                            <xs:minExclusive value="0"/>
                            <xs:maxInclusive value="9999999"/>
                        </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="uroven">
                <xs:simpleType>
                        <xs:restriction base="xs:string">
                              <xs:enumeration value="Začátečník"/>
                              <xs:enumeration value="Mírně pokročilý"/>
                              <xs:enumeration value="Pokročilý"/>
                              <xs:enumeration value="Profesionál"/>
                        </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="country">
                <xs:simpleType>
                        <xs:restriction base="xs:string">
                              <xs:enumeration value="Czech"/>
                              <xs:enumeration value="USA"/>
                              <xs:enumeration value="Germany"/>
                        </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="jmeno" type="xs:string"/>
            <xs:attribute name="avatar">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Avatar01"/>
                        <xs:enumeration value="Avatar02"/>
                        <xs:enumeration value="Avatar03"/>
                        <xs:enumeration value="Avatar04"/>
                        <xs:enumeration value="Avatar05"/>
                        <xs:enumeration value="Avatar06"/>
                        <xs:enumeration value="Avatar07"/>
                        <xs:enumeration value="Avatar08"/>
                        <xs:enumeration value="Avatar09"/>
                        <xs:enumeration value="Avatar10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="ujetokm">
                <xs:simpleType>
                        <xs:restriction base="xs:nonNegativeInteger">
                            <xs:minExclusive value="0"/>
                            <xs:maxInclusive value="9999999"/>
                        </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
    </xs:element>
</xs:schema>

=== xmarv023/Znackovaci-jazyky/nastaveni.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Nastaveni hry Euro Truck Simulator 2 -->
<databazeNastaveniUzivatelu  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchema.xsd">
    <nastaveni iduzivatele="1" country="Czech" uroven="Začátečník" jmeno="Vojta" avatar="Avatar01" ujetokm="623">
        <zobrazeni api="directX11" default-zobrazeni="no">
            <cela_obrazovka>true</cela_obrazovka>
            <jas>50</jas>
            <rozliseni>1080p</rozliseni>
            <obnovovaci_frekvence>60</obnovovaci_frekvence>                 
            <vertikalni_synchronizace>true</vertikalni_synchronizace>
            <MLAA>false</MLAA>
            <HDR>false</HDR>
            <DOF>true</DOF>
            <slunecni_paprsky>true</slunecni_paprsky>
            <korekce_barev>true</korekce_barev>
            <detaily_odlesku>Střední</detaily_odlesku>
            <kvalita_vegetace>Nízká</kvalita_vegetace>
            <hustota_travy>Vypnuto</hustota_travy>
            <kvalita_stinu>Střední</kvalita_stinu>
            <velikost_stinove_textury>Nízká</velikost_stinove_textury>
            <kvalita_pocasi>Střední</kvalita_pocasi>
            <kvalita_zrcatek>Nízká</kvalita_zrcatek>
            <vykreslovana_vzdalenost_zrcatek>Nízká</vykreslovana_vzdalenost_zrcatek>
            <kvalita_textur>Střední</kvalita_textur>
            <anizotropni_filtrovani>20</anizotropni_filtrovani>
            <normalove_mapovani>true</normalove_mapovani>
            <hlavni_svetla_vozidel>true</hlavni_svetla_vozidel>
            <vedlejsi_svetla_vozidel>true</vedlejsi_svetla_vozidel>
            <vykreslovana_vzdalenost_svetel>Nízká</vykreslovana_vzdalenost_svetel>
            <chodci>true</chodci>
        </zobrazeni>

        <zvuk vystup="reproduktor" default-zvuk="no">
            <celkova_hlasitost>66</celkova_hlasitost>
            <hlasitost_efektu>100</hlasitost_efektu>
            <hlasitost_hudby>30</hlasitost_hudby>
            <prevratit_stereo>false</prevratit_stereo>
            <zvukove_efekty>true</zvukove_efekty>
            <hudba>true</hudba>
            <zvukovy_signal_pri_couvani>true</zvukovy_signal_pri_couvani>
            <hlucne_vodici_cary>true</hlucne_vodici_cary>     
        </zvuk>
    </nastaveni>
    <nastaveni iduzivatele="2" country="Germany" uroven="Pokročilý" jmeno="Ulrich" avatar="Avatar08" ujetokm="2323">
        <zobrazeni api="directX11" default-zobrazeni="no">
            <cela_obrazovka>true</cela_obrazovka>
            <jas>50</jas>
            <rozliseni>1080p</rozliseni>
            <obnovovaci_frekvence>60</obnovovaci_frekvence>
            <vertikalni_synchronizace>true</vertikalni_synchronizace>
            <MLAA>true</MLAA>
            <HDR>false</HDR>
            <DOF>true</DOF>
            <slunecni_paprsky>false</slunecni_paprsky>
            <korekce_barev>true</korekce_barev>
            <detaily_odlesku>Vysoká</detaily_odlesku>
            <kvalita_vegetace>Vysoká</kvalita_vegetace>
            <hustota_travy>Vypnuto</hustota_travy>
            <kvalita_stinu>Vysoká</kvalita_stinu>
            <velikost_stinove_textury>Vysoká</velikost_stinove_textury>
            <kvalita_pocasi>Vysoká</kvalita_pocasi>
            <kvalita_zrcatek>Nízká</kvalita_zrcatek>
            <vykreslovana_vzdalenost_zrcatek>Nízká</vykreslovana_vzdalenost_zrcatek>
            <kvalita_textur>Střední</kvalita_textur>
            <anizotropni_filtrovani>20</anizotropni_filtrovani>
            <normalove_mapovani>true</normalove_mapovani>
            <hlavni_svetla_vozidel>true</hlavni_svetla_vozidel>
            <vedlejsi_svetla_vozidel>true</vedlejsi_svetla_vozidel>
            <vykreslovana_vzdalenost_svetel>Nízká</vykreslovana_vzdalenost_svetel>
            <chodci>true</chodci>
        </zobrazeni>

        <zvuk vystup="sluchatka" default-zvuk="yes">
            <celkova_hlasitost>66</celkova_hlasitost>
            <hlasitost_efektu>1</hlasitost_efektu>
            <hlasitost_hudby>30</hlasitost_hudby>
            <prevratit_stereo>false</prevratit_stereo>
            <zvukove_efekty>false</zvukove_efekty>
            <hudba>true</hudba>
            <zvukovy_signal_pri_couvani>true</zvukovy_signal_pri_couvani>
            <hlucne_vodici_cary>false</hlucne_vodici_cary>
        </zvuk>
    </nastaveni>
    <nastaveni iduzivatele="3" country="Czech" uroven="Pokročilý" jmeno="Kristýna" avatar="Avatar02" ujetokm="1612">
        <zobrazeni api="directX11" default-zobrazeni="yes">
            <cela_obrazovka>false</cela_obrazovka>
            <jas>40</jas>
            <rozliseni>720p</rozliseni>
            <obnovovaci_frekvence>60</obnovovaci_frekvence>
            <vertikalni_synchronizace>true</vertikalni_synchronizace>
            <MLAA>false</MLAA>
            <HDR>false</HDR>
            <DOF>false</DOF>
            <slunecni_paprsky>true</slunecni_paprsky>
            <korekce_barev>true</korekce_barev>           
            <detaily_odlesku>Vysoká</detaily_odlesku>
            <kvalita_vegetace>Vysoká</kvalita_vegetace>
            <hustota_travy>Vypnuto</hustota_travy>
            <kvalita_stinu>Vysoká</kvalita_stinu>
            <velikost_stinove_textury>Vysoká</velikost_stinove_textury>
            <kvalita_pocasi>Vysoká</kvalita_pocasi>
            <kvalita_zrcatek>Nízká</kvalita_zrcatek>
            <vykreslovana_vzdalenost_zrcatek>Nízká</vykreslovana_vzdalenost_zrcatek>
            <kvalita_textur>Střední</kvalita_textur>
            <anizotropni_filtrovani>20</anizotropni_filtrovani>
            <normalove_mapovani>true</normalove_mapovani>
            <hlavni_svetla_vozidel>true</hlavni_svetla_vozidel>
            <vedlejsi_svetla_vozidel>true</vedlejsi_svetla_vozidel>
            <vykreslovana_vzdalenost_svetel>Nízká</vykreslovana_vzdalenost_svetel>
            <chodci>true</chodci>
        </zobrazeni>

        <zvuk vystup="reproduktor" default-zvuk="no">
            <celkova_hlasitost>100</celkova_hlasitost>
            <hlasitost_efektu>100</hlasitost_efektu>
            <hlasitost_hudby>80</hlasitost_hudby>
            <prevratit_stereo>false</prevratit_stereo>
            <zvukove_efekty>true</zvukove_efekty>
            <hudba>true</hudba>
            <zvukovy_signal_pri_couvani>false</zvukovy_signal_pri_couvani>
            <hlucne_vodici_cary>true</hlucne_vodici_cary>
        </zvuk>
    </nastaveni>
    <nastaveni iduzivatele="4" country="USA" uroven="Začátečník" jmeno="Tom" avatar="Avatar05" ujetokm="52">
        <zobrazeni api="directX11" default-zobrazeni="no">
            <cela_obrazovka>true</cela_obrazovka>
            <jas>70</jas>
            <rozliseni>1080p</rozliseni>
            <obnovovaci_frekvence>60</obnovovaci_frekvence>
            <vertikalni_synchronizace>false</vertikalni_synchronizace>
            <MLAA>true</MLAA>
            <HDR>false</HDR>
            <DOF>false</DOF>
            <slunecni_paprsky>true</slunecni_paprsky>
            <korekce_barev>true</korekce_barev>
            <detaily_odlesku>Vysoká</detaily_odlesku>
            <kvalita_vegetace>Vysoká</kvalita_vegetace>
            <hustota_travy>Vypnuto</hustota_travy>
            <kvalita_stinu>Vysoká</kvalita_stinu>
            <velikost_stinove_textury>Vysoká</velikost_stinove_textury>
            <kvalita_pocasi>Vysoká</kvalita_pocasi>
            <kvalita_zrcatek>Nízká</kvalita_zrcatek>
            <vykreslovana_vzdalenost_zrcatek>Nízká</vykreslovana_vzdalenost_zrcatek>
            <kvalita_textur>Střední</kvalita_textur>
            <anizotropni_filtrovani>20</anizotropni_filtrovani>
            <normalove_mapovani>true</normalove_mapovani>
            <hlavni_svetla_vozidel>true</hlavni_svetla_vozidel>
            <vedlejsi_svetla_vozidel>true</vedlejsi_svetla_vozidel>
            <vykreslovana_vzdalenost_svetel>Nízká</vykreslovana_vzdalenost_svetel>
            <chodci>false</chodci>
        </zobrazeni>

        <zvuk vystup="sluchatka" default-zvuk="no">
            <celkova_hlasitost>100</celkova_hlasitost>
            <hlasitost_efektu>100</hlasitost_efektu>
            <hlasitost_hudby>80</hlasitost_hudby>
            <prevratit_stereo>false</prevratit_stereo>
            <zvukove_efekty>false</zvukove_efekty>
            <hudba>true</hudba>
            <zvukovy_signal_pri_couvani>false</zvukovy_signal_pri_couvani>
            <hlucne_vodici_cary>true</hlucne_vodici_cary>
        </zvuk>
    </nastaveni>
    <nastaveni iduzivatele="5" country="USA" uroven="Začátečník" jmeno="Lucia" avatar="Avatar02" ujetokm="3">
        <zobrazeni api="directX11" default-zobrazeni="no">
            <cela_obrazovka>false</cela_obrazovka>
            <jas>50</jas>
            <rozliseni>720p</rozliseni>
            <obnovovaci_frekvence>60</obnovovaci_frekvence>
            <vertikalni_synchronizace>true</vertikalni_synchronizace>
            <MLAA>true</MLAA>
            <HDR>true</HDR>
            <DOF>true</DOF>
            <slunecni_paprsky>true</slunecni_paprsky>
            <korekce_barev>true</korekce_barev>
            <detaily_odlesku>Vysoká</detaily_odlesku>
            <kvalita_vegetace>Vysoká</kvalita_vegetace>
            <hustota_travy>Vypnuto</hustota_travy>
            <kvalita_stinu>Vysoká</kvalita_stinu>
            <velikost_stinove_textury>Vysoká</velikost_stinove_textury>
            <kvalita_pocasi>Vysoká</kvalita_pocasi>
            <kvalita_zrcatek>Nízká</kvalita_zrcatek>
            <vykreslovana_vzdalenost_zrcatek>Nízká</vykreslovana_vzdalenost_zrcatek>
            <kvalita_textur>Střední</kvalita_textur>
            <anizotropni_filtrovani>20</anizotropni_filtrovani>
            <normalove_mapovani>true</normalove_mapovani>
            <hlavni_svetla_vozidel>true</hlavni_svetla_vozidel>
            <vedlejsi_svetla_vozidel>true</vedlejsi_svetla_vozidel>
            <vykreslovana_vzdalenost_svetel>Nízká</vykreslovana_vzdalenost_svetel>
            <chodci>false</chodci>
        </zobrazeni>
